syshealthmental/apps/patient/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^list', views.patient_list, name='patient_list'),
    url(r'^(?P<pk>\d+)/detail$', views.patient_detail, name='patient_detail'),
    url(r'^new', views.patient_new, name='patient_new'),
    url(r'^(?P<pk>\d+)/edit$', views.patient_edit, name='patient_edit'),
]

syshealthmental/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^patient/', include('syshealthmental.apps.patient.urls')),
]

syshealthmental/apps/patient/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from syshealthmental.apps.patient.validators import validate_rg, validate_cpf, validate_phone, validate_cep

# Create your models here.


class Patient(models.Model):

    GENDER_CHOICES = (
        ('F', 'Feminino'),
        ('M', 'Masculino')
    )
    CIVIL_STATUS_CHOICES = (
        ('S', 'Solteiro (a)'),
        ('C', 'Casado (a)'),
        ('SE', 'Separado (a)'),
        ('D', 'Divorciado (a)'),
        ('V', 'Viúvo (a)'),
    )
    SCHOLARITY_CHOICES = (
        ('FI', 'Fundamental Incompleto'),
        ('FC', 'Fundamental Completo'),
        ('MI', 'Médio Incompleto'),
        ('MC', 'Médio Completo'),
        ('SI', 'Superior Incompleto'),
        ('SC', 'Superior Completo'),
        ('PGI', 'Pós-graduação Incompleto'),
        ('PGC', 'Pós-graduação Completo'),
        ('MEI', 'Mestrado Incompleto'),
        ('MEC', 'Mestrado Completo'),
        ('DOI', 'Doutorado Incompleto'),
        ('DOC', 'Doutorado Completo'),
    )
    FAMILY_INCOME_CHOICES = (
        ('SR', 'Não possui renda'),
        ('MU', 'Meio até 1 salário mínimo'),
        ('DT', '2 até 3 salários mínimos'),
        ('QC', '4 até 5 salários mínimos'),
        ('CM', '5 salários mínimos ou mais'),
    )
    name = models.CharField(
        u'Nome Completo', max_length=255
    )
    nickname = models.CharField(
        u'Apelido', max_length=25, blank=True
    )
    date_of_birth = models.DateField(
        u'Data de nascimento'
    )
    age = models.CharField(
        u'Idade', max_length=3
    )
    gender = models.CharField(
        u'Sexo', max_length=1, choices=GENDER_CHOICES
    )
    mother_name = models.CharField(
        u'Mãe', max_length=255
    )
    father_name = models.CharField(
        u'Pai', max_length=255, blank=True
    )
    cns = models.CharField(
        u'Cartão Nacional de Saúde', max_length=255, unique=True
    )
    cpf = models.CharField(
        u'CPF', max_length=11, unique=True, validators=[validate_cpf]
    )
    rg = models.CharField(
        u'Registro Geral', max_length=255, validators=[validate_rg]
    )
    date_of_expedition = models.DateField(
        u'Data de Expedição'
    )
    nationality = models.CharField(
        u'Nacionalidade', max_length=255, blank=True
    )
    civil_status = models.CharField(
        u'Estado Civil', max_length=2, choices=CIVIL_STATUS_CHOICES, blank=True
    )
    children = models.CharField(
        u'Filhos', max_length=3, blank=True
    )
    scholarity = models.CharField(
        u'Escolaridade', max_length=3, choices=SCHOLARITY_CHOICES, blank=True
    )
    ethnicity = models.CharField(
        u'Etnia', max_length=255, blank=True
    )
    phone = models.CharField(
        u'Telefone', max_length=11, validators=[validate_phone]
    )
    live_with = models.CharField(
        u'Reside com', max_length=255, blank=True
    )
    address = models.CharField(
        u'Endereço', max_length=255, blank=True
    )
    cep = models.CharField(
        u'CEP', max_length=8, validators=[validate_cep], blank=True
    )
    landmark = models.CharField(
        u'Ponto de Referência', max_length=255, blank=True
    )
    workplace = models.CharField(
        u'Local de trabalho', max_length=255, blank=True
    )
    profession = models.CharField(
        u'Profissão', max_length=100, blank=True
    )
    family_income = models.CharField(
        u'Renda', max_length=2, choices=FAMILY_INCOME_CHOICES, blank=True
    )

    @property
    def full_name(self):
        return self.name

    @property
    def short_name(self):
        name = self.name.split(' ')
        if len(name) > 1:
            return '%s %s' % (name[0], name[1])
        else:
            return name[0]

    @property
    def first_name(self):
        return '%s' % self.name.split(' ')[0]

    def __unicode__(self):
        return u'Paciente %s - %s' % (self.cpf, self.name)

syshealthmental/apps/patient/forms.py
# -*- coding:utf-8 -*-

from django import forms
from syshealthmental.apps.patient.validators import validate_cpf, only_digits, validate_phone, validate_cep
from syshealthmental.apps.patient.models import Patient
from localflavor.br.forms import BRPhoneNumberField

class PatientForm(forms.ModelForm):

    phone = BRPhoneNumberField(
        error_messages={'invalid': ('Número inválido.'
                                    'Formatos permitidos: XX-XXXX-XXXX'
                                    ' ou XX-XXXXX-XXXX')},
    )

    cpf = forms.CharField(max_length=14)
    phone = forms.CharField(max_length=15)
    cep = forms.CharField(max_length=9)


    def clean_cpf(self):
        cpf = only_digits(self.cleaned_data['cpf'])
        validate_cpf(cpf)
        if Patient.objects.filter(cpf=cpf).exists():
            instance_cpf_exists = Patient.objects.get(cpf=cpf)

            instance = getattr(self, 'instance', None)

            if instance == instance_cpf_exists:
                pass
            else:
                raise forms.ValidationError(u'Esse CPF já pertence a outro paciente')
        return cpf

    def clean_phone(self):
        phone = only_digits(self.cleaned_data['phone'])

        return validate_phone(phone)

    def clean_cep(self):

        cep = only_digits(self.cleaned_data['cep'])

        return validate_cep(cep)

    class Meta:
        model = Patient
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs = {'required': True}),
            'date_of_birth': forms.DateInput(format=('%d/%m/%Y'), attrs = {'required': True}),
            'mother_name': forms.TextInput(attrs = {'required': True}),
            'cns': forms.TextInput(attrs = {'required': True}),
            'cpf': forms.TextInput(attrs = {'required': True}),
            'rg': forms.TextInput(attrs = {'required': True}),
            'date_of_expedition': forms.DateInput(format=('%d/%m/%Y'), attrs = {'required': True}),
            'age': forms.TextInput(attrs = {'required': True}),
            'phone': forms.TextInput(attrs = {'required': True}),
            'cep': forms.TextInput(attrs = {'required': True}),

        }

syshealthmental/apps/patient/views.py
# -*- coding:utf-8 -*-
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from syshealthmental.apps.patient.forms import PatientForm
from syshealthmental.apps.patient.models import Patient
# Create your views here.

def patient_list(request):
    patients_list = Patient.objects.all().order_by('name')
    page = request.GET.get('page')

    paginator = Paginator(patients_list, 5)
    try:
        patients = paginator.page(page)
    except PageNotAnInteger:
        patients = paginator.page(1)
    except EmptyPage:
        patients = paginator.page(paginator.num_pages)

    return render(request, 'patient/patient_list.html', {'patients': patients})

def patient_detail(request, pk):
    patient = get_object_or_404(Patient, pk=pk)
    return render(request, 'patient/patient_detail.html', {'patient': patient})

def patient_new(request):
    if request.method == 'POST':
        form = PatientForm(request.POST)

        if form.is_valid():
            patient = form.save()
            return redirect('patient_detail', pk=patient.pk)
    else:
        form = PatientForm()
    return render(request, 'patient/patient_new.html', {'form': form})

def patient_edit(request, pk):
    patient = get_object_or_404(Patient, pk=pk)

    if request.method == 'POST':
        form = PatientForm(request.POST, instance=patient)
        if form.is_valid():
            patient = form.save()
            return redirect('patient_detail', pk=patient.pk)
    else:
        form = PatientForm(instance=patient)
    return render(request, 'patient/patient_edit.html', {'patient': form})

syshealthmental/apps/patient/templates/patient/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}{% endblock %} SysHealthMental {% block current_host %}{% endblock %}</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Third Party -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


  {% block stylesheets %}
  {% endblock %}

</head>
<body>

    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom border-gray">
        <a class="navbar-brand" href="">GPSM</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            &nbsp;
          </ul>

          <ul class="nav navbar-nav navbar-right">
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                  <span>Bem vindo</span>

                </a>
                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink" role="menu">
                  <li>
                    <a class="dropdown-item" href="">Alterar Perfil</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'patient_list' %}">Área Pacientes</a>
                  </li>

                  <li>
                    <a class="dropdown-item" href="">Área Funcionários</a>
                  </li>
                  <li>
                      <a class="dropdown-item" href=""
                          onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">
                              Sair
                      </a>

                      <form id="logout-form" action="" method="POST" style="display: none;">

                      </form>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </nav>
        </div>
    {% endblock %}

    {% block messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endblock %}

    {% block content %}

    {% endblock %}

    <!-- Modal -->
    {% block modal %}
    {% endblock %}

    <!-- SCRIPTS -->

    <!-- Third Party -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script>window.jQuery || document.write("<script src=\"{% static 'scripts/jquery-3.2.1.slim.min.js' %}\"><\/script>")</script>
    <!-- Latest compiled and minified Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static 'scripts/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script type="text/javascript" src="{% static 'scripts/popper.min.js'%}"></script>


    {% comment %}

    {% endcomment %}

    {% block scripts %}
    {% endblock %}

</body>
</html>

syshealthmental/apps/patient/templates/patient/patient_detail.html
{% extends 'patient/base.html' %}
{% load staticfiles %}
{% load base %}

{% block content %}
<div class="container">
  <div class="d-flex flex-row-reverse mx-3 my-3">

      <a href="{% url 'patient_edit' pk=patient.pk %}" class="btn btn-outline-secondary rounded btn-sm">Editar</a>

  </div>
  <!-- Dados pessoais -->
  <div class="bg-light border-left border-bottom rounded">
    <h3 class="border-gray border-bottom mx-3 my-3">Dados Pessoais</h3>

    <div class="form-row mx-3">
      <div class="form-group col-md-8">
        <label for="name">Nome Completo</label>
        <input type="text" name="name" class="form-control-sm form-control" id="name" value="{{patient.name}}" disabled>
      </div>
      <div class="form-group col-md-4">
        <label for="nickname">Apelido</label>
        <input type="text" name="nickname" class="form-control form-control-sm" id="nickname" value="{{patient.nickname}}" disabled>
      </div>
    </div>
    <div class="form-row mx-3">
      <div class="form-group col-md-2">
        <label for="date_of_birth">Data de Nascimento</label>
        <input type="text" name="date_of_birth" class="form-control form-control-sm" id="date_of_birth" value="{{patient.date_of_birth|date:"d/m/Y"}}" disabled>
      </div>
      <div class="form-group col-md-2">
        <label for="age">Idade</label>
        <input type="text" name="age" class="form-control-sm form-control" id="age" value="{{patient.age}}" disabled>
      </div>
      <div class="form-group col-md-3">
        <label for="gender">Sexo</label>
        <input type="text" name="gender" class="form-control-sm form-control" id="gender" value="{{patient.get_gender_display}}" disabled>
      </div>
    </div>
    <div class="form-row mx-3">
      <div class="form-group col-md-6">
        <label for="mother_name">Mãe</label>
        <input type="text" name="mother_name" class="form-control-sm form-control" id="mother_name" value="{{ patient.mother_name }}" disabled>
      </div>
      <div class="form-group col-md-6">
        <label for="father_name">Pai</label>
        <input type="text" name="father_name" class="form-control-sm form-control" id="father_name" value="{{ patient.father_name }}" disabled>
      </div>
    </div>
    <div class="form-row mx-3">
      <div class="form-group col-md-3">
        <label for="cns">CNS</label>
        <input type="text" name="cns" class="form-control form-control-sm" id="cns" value="{{patient.cns}}" disabled>
      </div>
      <div class="form-group col-md-2">
        <label for="cpf">CPF</label>
        <input type="text" name="cpf" class="form-control form-control-sm" id="cpf" value="{{patient.cpf|mask_cpf}}" disabled>
      </div>
      <div class="form-group col-md-2">
        <label for="rg">RG</label>
        <input type="text" name="rg" class="form-control form-control-sm" id="rg" value="{{patient.rg}}" disabled>
      </div>
      <div class="form-group col-md-2">
        <label for="date_of_expedition">Data de Expedição</label>
        <input type="text" name="date_of_expedition" class="form-control form-control-sm" id="date_of_expedition" value="{{patient.date_of_expedition|date:"d/m/Y"}}" disabled>
      </div>
      <div class="form-group col-md-3">
        <label for="nationality">Nacionalidade</label>
        <input type="text" name="nationality" class="form-control form-control-sm" id="nationality" value="{{patient.nationality}}" disabled>
      </div>
    </div>
    <div class="form-row mx-3">
      <div class="form-group col-md-2">
        <label for="ethnicity">Etnia</label>
        <input type="text" name="ethnicity" class="form-control form-control-sm" id="ethnicity" value="{{patient.ethnicity}}" disabled>
      </div>
      <div class="form-group col-md-2">
        <label for="civil_status">Estado Civil</label>
        <input type="text" name="civil_status" class="form-control form-control-sm" id="civil_status" value="{{patient.get_civil_status_display}}" disabled>
      </div>
      <div class="form-group col-md-2">
        <label for="children">Número de filhos</label>
        <input type="text" name="children" class="form-control form-control-sm" id="children" value="{{patient.children}}" disabled>
      </div>
      <div class="form-group col-md-3">
        <label for="scholarity">Escolaridade</label>
        <input type="text" name="scholarity" class="form-control form-control-sm" id="scholarity" value="{{patient.get_scholarity_display}}" disabled>
      </div>
      <div class="form-group col-md-3">
        <label for="phone">Telefone</label>
        <input type="text" name="phone" class="form-control form-control-sm" id="phone" value="{{patient.phone|mask_phone}}" disabled>
      </div>
    </div>
  </div>

  <div class="bg-light border-left border-bottom rounded">
    <h3 class="border-gray border-bottom mx-3 my-3">Dados Residencias</h3>
    <div class="form-row mx-3">
      <div class="form-group col-md-8">
        <label for="address">Endereço</label>
        <input type="text" name="address" class="form-control form-control-sm" id="address" value="{{patient.address}}" disabled>
      </div>

      <div class="form-group col-md-2">
        <label for="cep">CEP*</label>
        <input type="text" name="cep" class="form-control form-control-sm" id="cep" value="{{patient.cep|mask_cep}}" disabled>
      </div>
    </div>
    <div class="form-row mx-3">
      <div class="form-group col-md-5">
        <label for="landmark">Ponto de Referência</label>
        <input type="text" name="landmark" class="form-control form-control-sm" id="landmark" value="{{patient.landmark}}" disabled>
      </div>

      <div class="form-group col-md-5">
        <label for="live_with">Com quem Reside</label>
        <input type="text" name="live_with" class="form-control form-control-sm" id="live_with" value="{{patient.live_with}}" disabled>
      </div>
    </div>
  </div>

  <div class="bg-light border-left border-bottom rounded">
    <h3 class="border-gray border-bottom mx-3 my-3">Dados Profissionais</h3>
    <div class="form-row mx-3">
      <div class="form-group col-md-4">
        <label for="profession">Profissão</label>
        <input type="text" name="profession" class="form-control form-control-sm" id="profession" value="{{patient.profession}}" disabled>
      </div>
      <div class="form-group col-md-4">
        <label for="workplace">Local de Trabalho</label>
        <input type="text" name="workplace" class="form-control form-control-sm" id="workplace" value="{{patient.workplace}}" disabled>
      </div>
      <div class="form-group col-md-4">
        <label for="family_income">Renda</label>
        <input type="text" name="family_income" class="form-control form-control-sm" id="family_income" value="{{patient.get_family_income_display}}" disabled>
      </div>
    </div>
  </div>
</div>
{% endblock %}

syshealthmental/apps/patient/templates/patient/patient_list.html
{% extends "patient/base.html" %}
{% load staticfiles %}
{% load base %}

{% block content %}
<div class="container">
  <div class="top-left mx-3 my-3">
      <div class="btn-toolbar" role="toolbar">
          <div class="btn-group" role="group">
              <a href="{% url 'patient_new' %}" class="btn btn-success rounded btn-sm" data-toggle="tooltip" data-placement="bottom" title="Cadastrar paciente">Cadastrar</a>
          </div>
      </div>
  </div>

  <form action="">
    <nav class="navbar navbar-light bg-light mx-3 my-3">
      <input class="form-control mr-sm-2 col-md-6" name="search" type="search" placeholder="Consultar por Nome ou CPF ou CNS" aria-label="Search">
    </nav>
  </form>

  <table class="table table-bordered table-responsive-sm table-hover table-sm text-center">
    <thead>
      <tr>
        <th scope="col" style="width: 20%;">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">Data de Nascimento</th>
        <th scope="col">CNS</th>
        <th scope="col">Opções</th>
        <th scope="col">Triagem/Retriagem</th>
        <th scope="col">Evolução</th>
      </tr>
    </thead>
    <tbody>
      {% for p in patients %}
      <tr>
        <td>{{ p.name }}</td>
        <td>{{ p.cpf|mask_cpf }}</td>
        <td>{{ p.date_of_birth|date:"d/m/Y" }}</td>
        <td>{{ p.cns }}</td>
        <td>
          <a href="{% url 'patient_detail' pk=p.pk %}" class="btn btn-outline-success btn-sm rounded mb-1">Visualizar</a>
          <a href="{% url 'patient_edit' pk=p.pk %}" class="btn btn-outline-secondary rounded btn-sm mb-1">Atualizar</a>
        </td>
        <td>
            <a href="" class="btn btn-outline-success rounded btn-sm">Avançar</a>
        </td>
        <td>
            <a href="" class="btn btn-outline-success rounded btn-sm">Avançar</a>

        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% if patients.has_other_pages %}
  <ul class="pagination justify-content-center">
    {% if patients.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ patients.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for i in patients.paginator.page_range %}
      {% if patients.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if patients.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ patients.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>
{% endblock %}